/********************************************************************************
** Form generated from reading UI file 'RayCaster.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_RAYCASTER_H
#define UI_RAYCASTER_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_RayCasterClass
{
public:
    QAction *m_actionNew;
    QAction *m_actionOpen;
    QAction *m_actionSave;
    QAction *m_actionQuit;
    QWidget *centralWidget;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *m_layoutV;
    QTabWidget *m_tabScene;
    QWidget *m_tabCamera;
    QGroupBox *m_grpBoxCamType;
    QRadioButton *m_rBtnPerspectiveCam;
    QRadioButton *m_rBtnOrthogonalCam;
    QGroupBox *m_grpBoxCamProperties;
    QDoubleSpinBox *m_dSBoxCamPosX;
    QDoubleSpinBox *m_dSBoxCamPosY;
    QDoubleSpinBox *m_dSBoxCamPosZ;
    QLabel *m_LblCamPos;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QDoubleSpinBox *m_dSBoxCamAngle;
    QLabel *label_7;
    QDoubleSpinBox *m_dSBoxCamDirZ;
    QDoubleSpinBox *m_dSBoxCamDirX;
    QLabel *m_LblCamPos_2;
    QLabel *label_5;
    QDoubleSpinBox *m_dSBoxCamDirY;
    QLabel *label_6;
    QLabel *label_4;
    QLabel *label_8;
    QDoubleSpinBox *m_dSBoxCamUpX;
    QLabel *label_9;
    QDoubleSpinBox *m_dSBoxCamUpY;
    QLabel *m_LblCamPos_3;
    QLabel *label_10;
    QDoubleSpinBox *m_dSBoxCamUpZ;
    QGroupBox *groupBox;
    QLabel *label_12;
    QLabel *label_11;
    QSpinBox *m_SBoxImgW;
    QSpinBox *m_SBoxImgH;
    QLineEdit *m_LEImgFilename;
    QLabel *label_46;
    QPushButton *m_BtnBrowseImg;
    QWidget *m_taLight;
    QGroupBox *groupBox_2;
    QListWidget *m_lightList;
    QPushButton *m_BtnLightAdd;
    QPushButton *m_BtnLightRemove;
    QGroupBox *groupBox_3;
    QLabel *label_13;
    QLabel *label_14;
    QDoubleSpinBox *m_dSBoxLightDirPosZ;
    QDoubleSpinBox *m_dSBoxLightDirPosX;
    QDoubleSpinBox *m_dSBoxLightDirPosY;
    QLabel *label_15;
    QLabel *m_LblLightPosDir;
    QLabel *m_LblCamPos_4;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QRadioButton *m_rBtnPointLight;
    QRadioButton *m_rBtnDirLight;
    QSpinBox *m_SBoxLightColR;
    QSpinBox *m_SBoxLightColG;
    QSpinBox *m_SBoxLightColB;
    QLineEdit *m_LELightName;
    QLabel *label_19;
    QGroupBox *groupBox_6;
    QSpinBox *m_SBoxBackColR;
    QSpinBox *m_SBoxBackColG;
    QLabel *label_49;
    QSpinBox *m_SBoxBackColB;
    QLabel *label_48;
    QLabel *m_LblCamPos_13;
    QLabel *label_47;
    QLabel *m_LblCamPos_14;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QSpinBox *m_SBoxAmbLightG;
    QSpinBox *m_SBoxAmbLightB;
    QSpinBox *m_SBoxAmbLightR;
    QWidget *m_tabObjects;
    QListWidget *m_objList;
    QGroupBox *groupBox_4;
    QTabWidget *m_objTab;
    QWidget *m_tabSphere;
    QDoubleSpinBox *m_dSBoxSphereCenterZ;
    QLabel *label_29;
    QDoubleSpinBox *m_dSBoxSphereCenterX;
    QLabel *m_LblCamPos_9;
    QLabel *label_30;
    QLabel *label_31;
    QDoubleSpinBox *m_dSBoxSphereCenterY;
    QLabel *label_32;
    QDoubleSpinBox *m_dSBoxSphereRadius;
    QWidget *m_tabPlane;
    QLabel *label_33;
    QLabel *m_LblCamPos_10;
    QLabel *label_34;
    QDoubleSpinBox *m_dSBoxPlaneNormalX;
    QLabel *label_35;
    QDoubleSpinBox *m_dSBoxPlaneOffset;
    QDoubleSpinBox *m_dSBoxPlaneNormalY;
    QDoubleSpinBox *m_dSBoxPlaneNormalZ;
    QLabel *label_36;
    QWidget *m_tabMesh;
    QLineEdit *m_LEMeshFile;
    QPushButton *m_btnBrowseMeshFile;
    QLabel *m_LblCamPos_11;
    QCheckBox *m_CBObjTransform;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *m_LblCamPos_5;
    QLabel *label_22;
    QDoubleSpinBox *m_dSBoxTransformRotationZ;
    QDoubleSpinBox *m_dSBoxTransformRotationX;
    QDoubleSpinBox *m_dSBoxTransformTranslateZ;
    QLabel *m_LblCamPos_6;
    QLabel *label_23;
    QDoubleSpinBox *m_dSBoxTransformTranslateX;
    QLabel *label_24;
    QDoubleSpinBox *m_dSBoxTransformScaleY;
    QDoubleSpinBox *m_dSBoxTransformTranslateY;
    QDoubleSpinBox *m_dSBoxTransformScaleX;
    QLabel *label_25;
    QLabel *m_LblCamPos_7;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QDoubleSpinBox *m_dSBoxTransformScaleZ;
    QDoubleSpinBox *m_dSBoxTransformRotationY;
    QComboBox *m_comboMaterial;
    QLabel *m_LblCamPos_8;
    QLineEdit *m_LEObjName;
    QLabel *label_44;
    QPushButton *m_btnRemoveObj;
    QPushButton *m_btnAddObj;
    QWidget *m_tabMaterial;
    QListWidget *m_materialsList;
    QGroupBox *groupBox_5;
    QLabel *label_37;
    QSpinBox *m_SBoxDifColB;
    QLabel *m_LblCamPos_12;
    QLabel *label_38;
    QLabel *label_39;
    QSpinBox *m_SBoxDifColG;
    QSpinBox *m_SBoxDifColR;
    QLabel *label_40;
    QSpinBox *m_SBoxSpecColR;
    QLabel *label_41;
    QSpinBox *m_SBoxSpecColB;
    QSpinBox *m_SBoxSpecColG;
    QLabel *label_42;
    QCheckBox *m_CBoxIsSpec;
    QLabel *label_43;
    QSpinBox *m_SBoxShininess;
    QLineEdit *m_LEMaterialName;
    QLabel *label_45;
    QLabel *label_53;
    QLineEdit *m_LETextureFile;
    QPushButton *m_BtnBrowseTextFile;
    QPushButton *m_BtnMaterialAdd;
    QPushButton *m_BtnMaterialRemove;
    QGraphicsView *m_graphicView;
    QPushButton *m_BtnRender;
    QProgressBar *m_pBarRendering;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *RayCasterClass)
    {
        if (RayCasterClass->objectName().isEmpty())
            RayCasterClass->setObjectName(QStringLiteral("RayCasterClass"));
        RayCasterClass->resize(1037, 678);
        m_actionNew = new QAction(RayCasterClass);
        m_actionNew->setObjectName(QStringLiteral("m_actionNew"));
        m_actionOpen = new QAction(RayCasterClass);
        m_actionOpen->setObjectName(QStringLiteral("m_actionOpen"));
        m_actionSave = new QAction(RayCasterClass);
        m_actionSave->setObjectName(QStringLiteral("m_actionSave"));
        m_actionQuit = new QAction(RayCasterClass);
        m_actionQuit->setObjectName(QStringLiteral("m_actionQuit"));
        centralWidget = new QWidget(RayCasterClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        verticalLayoutWidget = new QWidget(centralWidget);
        verticalLayoutWidget->setObjectName(QStringLiteral("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(640, 10, 391, 621));
        m_layoutV = new QVBoxLayout(verticalLayoutWidget);
        m_layoutV->setSpacing(6);
        m_layoutV->setContentsMargins(11, 11, 11, 11);
        m_layoutV->setObjectName(QStringLiteral("m_layoutV"));
        m_layoutV->setContentsMargins(0, 0, 0, 0);
        m_tabScene = new QTabWidget(verticalLayoutWidget);
        m_tabScene->setObjectName(QStringLiteral("m_tabScene"));
        m_tabCamera = new QWidget();
        m_tabCamera->setObjectName(QStringLiteral("m_tabCamera"));
        m_grpBoxCamType = new QGroupBox(m_tabCamera);
        m_grpBoxCamType->setObjectName(QStringLiteral("m_grpBoxCamType"));
        m_grpBoxCamType->setGeometry(QRect(0, 10, 381, 71));
        m_rBtnPerspectiveCam = new QRadioButton(m_grpBoxCamType);
        m_rBtnPerspectiveCam->setObjectName(QStringLiteral("m_rBtnPerspectiveCam"));
        m_rBtnPerspectiveCam->setGeometry(QRect(20, 20, 141, 17));
        m_rBtnPerspectiveCam->setChecked(true);
        m_rBtnOrthogonalCam = new QRadioButton(m_grpBoxCamType);
        m_rBtnOrthogonalCam->setObjectName(QStringLiteral("m_rBtnOrthogonalCam"));
        m_rBtnOrthogonalCam->setGeometry(QRect(20, 40, 141, 17));
        m_grpBoxCamProperties = new QGroupBox(m_tabCamera);
        m_grpBoxCamProperties->setObjectName(QStringLiteral("m_grpBoxCamProperties"));
        m_grpBoxCamProperties->setGeometry(QRect(0, 80, 381, 181));
        m_dSBoxCamPosX = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamPosX->setObjectName(QStringLiteral("m_dSBoxCamPosX"));
        m_dSBoxCamPosX->setGeometry(QRect(280, 40, 81, 22));
        m_dSBoxCamPosX->setMinimum(-100000);
        m_dSBoxCamPosX->setMaximum(100000);
        m_dSBoxCamPosY = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamPosY->setObjectName(QStringLiteral("m_dSBoxCamPosY"));
        m_dSBoxCamPosY->setGeometry(QRect(280, 70, 81, 22));
        m_dSBoxCamPosY->setMinimum(-10000);
        m_dSBoxCamPosY->setMaximum(10000);
        m_dSBoxCamPosZ = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamPosZ->setObjectName(QStringLiteral("m_dSBoxCamPosZ"));
        m_dSBoxCamPosZ->setGeometry(QRect(280, 100, 81, 22));
        m_dSBoxCamPosZ->setMinimum(-10000);
        m_dSBoxCamPosZ->setMaximum(10000);
        m_LblCamPos = new QLabel(m_grpBoxCamProperties);
        m_LblCamPos->setObjectName(QStringLiteral("m_LblCamPos"));
        m_LblCamPos->setGeometry(QRect(260, 20, 51, 16));
        label = new QLabel(m_grpBoxCamProperties);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(260, 40, 16, 16));
        label->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(m_grpBoxCamProperties);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(260, 70, 16, 16));
        label_2->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(m_grpBoxCamProperties);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(260, 100, 16, 16));
        label_3->setAlignment(Qt::AlignCenter);
        m_dSBoxCamAngle = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamAngle->setObjectName(QStringLiteral("m_dSBoxCamAngle"));
        m_dSBoxCamAngle->setGeometry(QRect(10, 150, 81, 22));
        m_dSBoxCamAngle->setMinimum(1);
        m_dSBoxCamAngle->setMaximum(180);
        label_7 = new QLabel(m_grpBoxCamProperties);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 130, 31, 16));
        label_7->setAlignment(Qt::AlignCenter);
        m_dSBoxCamDirZ = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamDirZ->setObjectName(QStringLiteral("m_dSBoxCamDirZ"));
        m_dSBoxCamDirZ->setGeometry(QRect(30, 100, 81, 22));
        m_dSBoxCamDirZ->setMinimum(-10000);
        m_dSBoxCamDirZ->setMaximum(10000);
        m_dSBoxCamDirX = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamDirX->setObjectName(QStringLiteral("m_dSBoxCamDirX"));
        m_dSBoxCamDirX->setGeometry(QRect(30, 40, 81, 22));
        m_dSBoxCamDirX->setMinimum(-1e+6);
        m_dSBoxCamDirX->setMaximum(100000);
        m_LblCamPos_2 = new QLabel(m_grpBoxCamProperties);
        m_LblCamPos_2->setObjectName(QStringLiteral("m_LblCamPos_2"));
        m_LblCamPos_2->setGeometry(QRect(10, 20, 51, 16));
        label_5 = new QLabel(m_grpBoxCamProperties);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 70, 16, 16));
        label_5->setAlignment(Qt::AlignCenter);
        m_dSBoxCamDirY = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamDirY->setObjectName(QStringLiteral("m_dSBoxCamDirY"));
        m_dSBoxCamDirY->setGeometry(QRect(30, 70, 81, 22));
        m_dSBoxCamDirY->setMinimum(-10000);
        m_dSBoxCamDirY->setMaximum(10000);
        label_6 = new QLabel(m_grpBoxCamProperties);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 40, 16, 16));
        label_6->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(m_grpBoxCamProperties);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 100, 16, 16));
        label_4->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(m_grpBoxCamProperties);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(140, 70, 16, 16));
        label_8->setAlignment(Qt::AlignCenter);
        m_dSBoxCamUpX = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamUpX->setObjectName(QStringLiteral("m_dSBoxCamUpX"));
        m_dSBoxCamUpX->setGeometry(QRect(160, 40, 81, 22));
        m_dSBoxCamUpX->setMinimum(-1e+6);
        m_dSBoxCamUpX->setMaximum(100000);
        label_9 = new QLabel(m_grpBoxCamProperties);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(140, 40, 16, 16));
        label_9->setAlignment(Qt::AlignCenter);
        m_dSBoxCamUpY = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamUpY->setObjectName(QStringLiteral("m_dSBoxCamUpY"));
        m_dSBoxCamUpY->setGeometry(QRect(160, 70, 81, 22));
        m_dSBoxCamUpY->setMinimum(-10000);
        m_dSBoxCamUpY->setMaximum(10000);
        m_LblCamPos_3 = new QLabel(m_grpBoxCamProperties);
        m_LblCamPos_3->setObjectName(QStringLiteral("m_LblCamPos_3"));
        m_LblCamPos_3->setGeometry(QRect(140, 20, 21, 16));
        label_10 = new QLabel(m_grpBoxCamProperties);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(140, 100, 16, 16));
        label_10->setAlignment(Qt::AlignCenter);
        m_dSBoxCamUpZ = new QDoubleSpinBox(m_grpBoxCamProperties);
        m_dSBoxCamUpZ->setObjectName(QStringLiteral("m_dSBoxCamUpZ"));
        m_dSBoxCamUpZ->setGeometry(QRect(160, 100, 81, 22));
        m_dSBoxCamUpZ->setMinimum(-10000);
        m_dSBoxCamUpZ->setMaximum(10000);
        groupBox = new QGroupBox(m_tabCamera);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(0, 260, 381, 81));
        label_12 = new QLabel(groupBox);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(130, 20, 41, 20));
        label_12->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(groupBox);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 20, 41, 20));
        label_11->setAlignment(Qt::AlignCenter);
        m_SBoxImgW = new QSpinBox(groupBox);
        m_SBoxImgW->setObjectName(QStringLiteral("m_SBoxImgW"));
        m_SBoxImgW->setGeometry(QRect(50, 20, 71, 22));
        m_SBoxImgW->setMinimum(1);
        m_SBoxImgW->setMaximum(10000);
        m_SBoxImgW->setValue(200);
        m_SBoxImgH = new QSpinBox(groupBox);
        m_SBoxImgH->setObjectName(QStringLiteral("m_SBoxImgH"));
        m_SBoxImgH->setGeometry(QRect(180, 20, 71, 22));
        m_SBoxImgH->setMinimum(1);
        m_SBoxImgH->setMaximum(10000);
        m_SBoxImgH->setValue(200);
        m_LEImgFilename = new QLineEdit(groupBox);
        m_LEImgFilename->setObjectName(QStringLiteral("m_LEImgFilename"));
        m_LEImgFilename->setGeometry(QRect(60, 50, 191, 20));
        label_46 = new QLabel(groupBox);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(10, 50, 51, 16));
        m_BtnBrowseImg = new QPushButton(groupBox);
        m_BtnBrowseImg->setObjectName(QStringLiteral("m_BtnBrowseImg"));
        m_BtnBrowseImg->setGeometry(QRect(260, 50, 51, 23));
        m_tabScene->addTab(m_tabCamera, QString());
        m_taLight = new QWidget();
        m_taLight->setObjectName(QStringLiteral("m_taLight"));
        groupBox_2 = new QGroupBox(m_taLight);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(0, 0, 381, 251));
        m_lightList = new QListWidget(groupBox_2);
        m_lightList->setObjectName(QStringLiteral("m_lightList"));
        m_lightList->setGeometry(QRect(10, 20, 361, 191));
        m_lightList->setSelectionBehavior(QAbstractItemView::SelectItems);
        m_BtnLightAdd = new QPushButton(groupBox_2);
        m_BtnLightAdd->setObjectName(QStringLiteral("m_BtnLightAdd"));
        m_BtnLightAdd->setGeometry(QRect(260, 220, 41, 23));
        m_BtnLightRemove = new QPushButton(groupBox_2);
        m_BtnLightRemove->setObjectName(QStringLiteral("m_BtnLightRemove"));
        m_BtnLightRemove->setGeometry(QRect(310, 220, 61, 23));
        groupBox_3 = new QGroupBox(m_taLight);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(0, 260, 381, 181));
        label_13 = new QLabel(groupBox_3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 110, 16, 16));
        label_13->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(groupBox_3);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 140, 16, 16));
        label_14->setAlignment(Qt::AlignCenter);
        m_dSBoxLightDirPosZ = new QDoubleSpinBox(groupBox_3);
        m_dSBoxLightDirPosZ->setObjectName(QStringLiteral("m_dSBoxLightDirPosZ"));
        m_dSBoxLightDirPosZ->setGeometry(QRect(30, 140, 81, 22));
        m_dSBoxLightDirPosZ->setMinimum(-100000);
        m_dSBoxLightDirPosZ->setMaximum(100000);
        m_dSBoxLightDirPosX = new QDoubleSpinBox(groupBox_3);
        m_dSBoxLightDirPosX->setObjectName(QStringLiteral("m_dSBoxLightDirPosX"));
        m_dSBoxLightDirPosX->setGeometry(QRect(30, 80, 81, 22));
        m_dSBoxLightDirPosX->setMinimum(-1e+6);
        m_dSBoxLightDirPosX->setMaximum(100000);
        m_dSBoxLightDirPosY = new QDoubleSpinBox(groupBox_3);
        m_dSBoxLightDirPosY->setObjectName(QStringLiteral("m_dSBoxLightDirPosY"));
        m_dSBoxLightDirPosY->setGeometry(QRect(30, 110, 81, 22));
        m_dSBoxLightDirPosY->setMinimum(-100000);
        m_dSBoxLightDirPosY->setMaximum(100000);
        label_15 = new QLabel(groupBox_3);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 80, 16, 16));
        label_15->setAlignment(Qt::AlignCenter);
        m_LblLightPosDir = new QLabel(groupBox_3);
        m_LblLightPosDir->setObjectName(QStringLiteral("m_LblLightPosDir"));
        m_LblLightPosDir->setGeometry(QRect(10, 60, 51, 16));
        m_LblCamPos_4 = new QLabel(groupBox_3);
        m_LblCamPos_4->setObjectName(QStringLiteral("m_LblCamPos_4"));
        m_LblCamPos_4->setGeometry(QRect(140, 60, 41, 16));
        label_16 = new QLabel(groupBox_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(140, 110, 41, 16));
        label_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_17 = new QLabel(groupBox_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(140, 140, 31, 16));
        label_17->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_18 = new QLabel(groupBox_3);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(140, 80, 31, 16));
        label_18->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_rBtnPointLight = new QRadioButton(groupBox_3);
        m_rBtnPointLight->setObjectName(QStringLiteral("m_rBtnPointLight"));
        m_rBtnPointLight->setGeometry(QRect(10, 20, 101, 17));
        m_rBtnPointLight->setChecked(true);
        m_rBtnDirLight = new QRadioButton(groupBox_3);
        m_rBtnDirLight->setObjectName(QStringLiteral("m_rBtnDirLight"));
        m_rBtnDirLight->setGeometry(QRect(10, 40, 101, 17));
        m_SBoxLightColR = new QSpinBox(groupBox_3);
        m_SBoxLightColR->setObjectName(QStringLiteral("m_SBoxLightColR"));
        m_SBoxLightColR->setGeometry(QRect(190, 80, 61, 22));
        m_SBoxLightColR->setMaximum(255);
        m_SBoxLightColR->setValue(255);
        m_SBoxLightColG = new QSpinBox(groupBox_3);
        m_SBoxLightColG->setObjectName(QStringLiteral("m_SBoxLightColG"));
        m_SBoxLightColG->setGeometry(QRect(190, 110, 61, 22));
        m_SBoxLightColG->setMaximum(255);
        m_SBoxLightColG->setValue(255);
        m_SBoxLightColB = new QSpinBox(groupBox_3);
        m_SBoxLightColB->setObjectName(QStringLiteral("m_SBoxLightColB"));
        m_SBoxLightColB->setGeometry(QRect(190, 140, 61, 22));
        m_SBoxLightColB->setMaximum(255);
        m_SBoxLightColB->setValue(255);
        m_LELightName = new QLineEdit(groupBox_3);
        m_LELightName->setObjectName(QStringLiteral("m_LELightName"));
        m_LELightName->setGeometry(QRect(190, 30, 181, 20));
        label_19 = new QLabel(groupBox_3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(140, 30, 47, 13));
        groupBox_6 = new QGroupBox(m_taLight);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(0, 440, 381, 131));
        m_SBoxBackColR = new QSpinBox(groupBox_6);
        m_SBoxBackColR->setObjectName(QStringLiteral("m_SBoxBackColR"));
        m_SBoxBackColR->setGeometry(QRect(60, 40, 61, 22));
        m_SBoxBackColR->setMaximum(255);
        m_SBoxBackColG = new QSpinBox(groupBox_6);
        m_SBoxBackColG->setObjectName(QStringLiteral("m_SBoxBackColG"));
        m_SBoxBackColG->setGeometry(QRect(60, 70, 61, 22));
        m_SBoxBackColG->setMaximum(255);
        label_49 = new QLabel(groupBox_6);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(10, 40, 31, 16));
        label_49->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_SBoxBackColB = new QSpinBox(groupBox_6);
        m_SBoxBackColB->setObjectName(QStringLiteral("m_SBoxBackColB"));
        m_SBoxBackColB->setGeometry(QRect(60, 100, 61, 22));
        m_SBoxBackColB->setMaximum(255);
        label_48 = new QLabel(groupBox_6);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(10, 100, 31, 16));
        label_48->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_LblCamPos_13 = new QLabel(groupBox_6);
        m_LblCamPos_13->setObjectName(QStringLiteral("m_LblCamPos_13"));
        m_LblCamPos_13->setGeometry(QRect(10, 20, 41, 16));
        label_47 = new QLabel(groupBox_6);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(10, 70, 41, 16));
        label_47->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_LblCamPos_14 = new QLabel(groupBox_6);
        m_LblCamPos_14->setObjectName(QStringLiteral("m_LblCamPos_14"));
        m_LblCamPos_14->setGeometry(QRect(160, 20, 71, 16));
        label_50 = new QLabel(groupBox_6);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(160, 70, 41, 16));
        label_50->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_51 = new QLabel(groupBox_6);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(160, 100, 31, 16));
        label_51->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_52 = new QLabel(groupBox_6);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(160, 40, 31, 16));
        label_52->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_SBoxAmbLightG = new QSpinBox(groupBox_6);
        m_SBoxAmbLightG->setObjectName(QStringLiteral("m_SBoxAmbLightG"));
        m_SBoxAmbLightG->setGeometry(QRect(210, 70, 61, 22));
        m_SBoxAmbLightG->setMaximum(255);
        m_SBoxAmbLightB = new QSpinBox(groupBox_6);
        m_SBoxAmbLightB->setObjectName(QStringLiteral("m_SBoxAmbLightB"));
        m_SBoxAmbLightB->setGeometry(QRect(210, 100, 61, 22));
        m_SBoxAmbLightB->setMaximum(255);
        m_SBoxAmbLightR = new QSpinBox(groupBox_6);
        m_SBoxAmbLightR->setObjectName(QStringLiteral("m_SBoxAmbLightR"));
        m_SBoxAmbLightR->setGeometry(QRect(210, 40, 61, 22));
        m_SBoxAmbLightR->setMaximum(255);
        m_tabScene->addTab(m_taLight, QString());
        m_tabObjects = new QWidget();
        m_tabObjects->setObjectName(QStringLiteral("m_tabObjects"));
        m_objList = new QListWidget(m_tabObjects);
        m_objList->setObjectName(QStringLiteral("m_objList"));
        m_objList->setGeometry(QRect(10, 10, 361, 201));
        m_objList->setSelectionBehavior(QAbstractItemView::SelectItems);
        groupBox_4 = new QGroupBox(m_tabObjects);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 240, 361, 341));
        m_objTab = new QTabWidget(groupBox_4);
        m_objTab->setObjectName(QStringLiteral("m_objTab"));
        m_objTab->setGeometry(QRect(10, 19, 341, 131));
        m_tabSphere = new QWidget();
        m_tabSphere->setObjectName(QStringLiteral("m_tabSphere"));
        m_dSBoxSphereCenterZ = new QDoubleSpinBox(m_tabSphere);
        m_dSBoxSphereCenterZ->setObjectName(QStringLiteral("m_dSBoxSphereCenterZ"));
        m_dSBoxSphereCenterZ->setGeometry(QRect(250, 30, 81, 22));
        m_dSBoxSphereCenterZ->setMinimum(-10000);
        m_dSBoxSphereCenterZ->setMaximum(10000);
        label_29 = new QLabel(m_tabSphere);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(230, 30, 16, 16));
        label_29->setAlignment(Qt::AlignCenter);
        m_dSBoxSphereCenterX = new QDoubleSpinBox(m_tabSphere);
        m_dSBoxSphereCenterX->setObjectName(QStringLiteral("m_dSBoxSphereCenterX"));
        m_dSBoxSphereCenterX->setGeometry(QRect(30, 30, 81, 22));
        m_dSBoxSphereCenterX->setMinimum(-1e+6);
        m_dSBoxSphereCenterX->setMaximum(100000);
        m_LblCamPos_9 = new QLabel(m_tabSphere);
        m_LblCamPos_9->setObjectName(QStringLiteral("m_LblCamPos_9"));
        m_LblCamPos_9->setGeometry(QRect(10, 10, 51, 16));
        label_30 = new QLabel(m_tabSphere);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(10, 30, 16, 16));
        label_30->setAlignment(Qt::AlignCenter);
        label_31 = new QLabel(m_tabSphere);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(120, 30, 16, 16));
        label_31->setAlignment(Qt::AlignCenter);
        m_dSBoxSphereCenterY = new QDoubleSpinBox(m_tabSphere);
        m_dSBoxSphereCenterY->setObjectName(QStringLiteral("m_dSBoxSphereCenterY"));
        m_dSBoxSphereCenterY->setGeometry(QRect(140, 30, 81, 22));
        m_dSBoxSphereCenterY->setMinimum(-10000);
        m_dSBoxSphereCenterY->setMaximum(10000);
        label_32 = new QLabel(m_tabSphere);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(10, 70, 41, 16));
        label_32->setAlignment(Qt::AlignCenter);
        m_dSBoxSphereRadius = new QDoubleSpinBox(m_tabSphere);
        m_dSBoxSphereRadius->setObjectName(QStringLiteral("m_dSBoxSphereRadius"));
        m_dSBoxSphereRadius->setGeometry(QRect(60, 70, 81, 22));
        m_dSBoxSphereRadius->setMinimum(-1e+6);
        m_dSBoxSphereRadius->setMaximum(100000);
        m_dSBoxSphereRadius->setValue(1);
        m_objTab->addTab(m_tabSphere, QString());
        m_tabPlane = new QWidget();
        m_tabPlane->setObjectName(QStringLiteral("m_tabPlane"));
        label_33 = new QLabel(m_tabPlane);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 30, 16, 16));
        label_33->setAlignment(Qt::AlignCenter);
        m_LblCamPos_10 = new QLabel(m_tabPlane);
        m_LblCamPos_10->setObjectName(QStringLiteral("m_LblCamPos_10"));
        m_LblCamPos_10->setGeometry(QRect(10, 10, 51, 16));
        label_34 = new QLabel(m_tabPlane);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(120, 30, 16, 16));
        label_34->setAlignment(Qt::AlignCenter);
        m_dSBoxPlaneNormalX = new QDoubleSpinBox(m_tabPlane);
        m_dSBoxPlaneNormalX->setObjectName(QStringLiteral("m_dSBoxPlaneNormalX"));
        m_dSBoxPlaneNormalX->setGeometry(QRect(30, 30, 81, 22));
        m_dSBoxPlaneNormalX->setMinimum(-1e+6);
        m_dSBoxPlaneNormalX->setMaximum(100000);
        label_35 = new QLabel(m_tabPlane);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 70, 41, 16));
        label_35->setAlignment(Qt::AlignCenter);
        m_dSBoxPlaneOffset = new QDoubleSpinBox(m_tabPlane);
        m_dSBoxPlaneOffset->setObjectName(QStringLiteral("m_dSBoxPlaneOffset"));
        m_dSBoxPlaneOffset->setGeometry(QRect(60, 70, 81, 22));
        m_dSBoxPlaneOffset->setMinimum(-1e+6);
        m_dSBoxPlaneOffset->setMaximum(100000);
        m_dSBoxPlaneNormalY = new QDoubleSpinBox(m_tabPlane);
        m_dSBoxPlaneNormalY->setObjectName(QStringLiteral("m_dSBoxPlaneNormalY"));
        m_dSBoxPlaneNormalY->setGeometry(QRect(140, 30, 81, 22));
        m_dSBoxPlaneNormalZ = new QDoubleSpinBox(m_tabPlane);
        m_dSBoxPlaneNormalZ->setObjectName(QStringLiteral("m_dSBoxPlaneNormalZ"));
        m_dSBoxPlaneNormalZ->setGeometry(QRect(250, 30, 81, 22));
        label_36 = new QLabel(m_tabPlane);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(230, 30, 16, 16));
        label_36->setAlignment(Qt::AlignCenter);
        m_objTab->addTab(m_tabPlane, QString());
        m_tabMesh = new QWidget();
        m_tabMesh->setObjectName(QStringLiteral("m_tabMesh"));
        m_LEMeshFile = new QLineEdit(m_tabMesh);
        m_LEMeshFile->setObjectName(QStringLiteral("m_LEMeshFile"));
        m_LEMeshFile->setGeometry(QRect(10, 30, 231, 20));
        m_btnBrowseMeshFile = new QPushButton(m_tabMesh);
        m_btnBrowseMeshFile->setObjectName(QStringLiteral("m_btnBrowseMeshFile"));
        m_btnBrowseMeshFile->setGeometry(QRect(250, 30, 51, 23));
        m_LblCamPos_11 = new QLabel(m_tabMesh);
        m_LblCamPos_11->setObjectName(QStringLiteral("m_LblCamPos_11"));
        m_LblCamPos_11->setGeometry(QRect(10, 10, 51, 16));
        m_objTab->addTab(m_tabMesh, QString());
        m_CBObjTransform = new QCheckBox(groupBox_4);
        m_CBObjTransform->setObjectName(QStringLiteral("m_CBObjTransform"));
        m_CBObjTransform->setGeometry(QRect(10, 160, 70, 17));
        label_20 = new QLabel(groupBox_4);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 230, 16, 16));
        label_20->setAlignment(Qt::AlignCenter);
        label_21 = new QLabel(groupBox_4);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(130, 230, 16, 16));
        label_21->setAlignment(Qt::AlignCenter);
        m_LblCamPos_5 = new QLabel(groupBox_4);
        m_LblCamPos_5->setObjectName(QStringLiteral("m_LblCamPos_5"));
        m_LblCamPos_5->setGeometry(QRect(130, 180, 31, 16));
        label_22 = new QLabel(groupBox_4);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(250, 260, 16, 16));
        label_22->setAlignment(Qt::AlignCenter);
        m_dSBoxTransformRotationZ = new QDoubleSpinBox(groupBox_4);
        m_dSBoxTransformRotationZ->setObjectName(QStringLiteral("m_dSBoxTransformRotationZ"));
        m_dSBoxTransformRotationZ->setEnabled(false);
        m_dSBoxTransformRotationZ->setGeometry(QRect(270, 260, 81, 22));
        m_dSBoxTransformRotationX = new QDoubleSpinBox(groupBox_4);
        m_dSBoxTransformRotationX->setObjectName(QStringLiteral("m_dSBoxTransformRotationX"));
        m_dSBoxTransformRotationX->setEnabled(false);
        m_dSBoxTransformRotationX->setGeometry(QRect(270, 200, 81, 22));
        m_dSBoxTransformRotationX->setMinimum(-100000);
        m_dSBoxTransformRotationX->setMaximum(100000);
        m_dSBoxTransformTranslateZ = new QDoubleSpinBox(groupBox_4);
        m_dSBoxTransformTranslateZ->setObjectName(QStringLiteral("m_dSBoxTransformTranslateZ"));
        m_dSBoxTransformTranslateZ->setEnabled(false);
        m_dSBoxTransformTranslateZ->setGeometry(QRect(30, 260, 81, 22));
        m_LblCamPos_6 = new QLabel(groupBox_4);
        m_LblCamPos_6->setObjectName(QStringLiteral("m_LblCamPos_6"));
        m_LblCamPos_6->setGeometry(QRect(10, 180, 61, 16));
        label_23 = new QLabel(groupBox_4);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 260, 16, 16));
        label_23->setAlignment(Qt::AlignCenter);
        m_dSBoxTransformTranslateX = new QDoubleSpinBox(groupBox_4);
        m_dSBoxTransformTranslateX->setObjectName(QStringLiteral("m_dSBoxTransformTranslateX"));
        m_dSBoxTransformTranslateX->setEnabled(false);
        m_dSBoxTransformTranslateX->setGeometry(QRect(30, 200, 81, 22));
        m_dSBoxTransformTranslateX->setMinimum(-1e+6);
        m_dSBoxTransformTranslateX->setMaximum(100000);
        label_24 = new QLabel(groupBox_4);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(250, 200, 16, 16));
        label_24->setAlignment(Qt::AlignCenter);
        m_dSBoxTransformScaleY = new QDoubleSpinBox(groupBox_4);
        m_dSBoxTransformScaleY->setObjectName(QStringLiteral("m_dSBoxTransformScaleY"));
        m_dSBoxTransformScaleY->setEnabled(false);
        m_dSBoxTransformScaleY->setGeometry(QRect(150, 230, 81, 22));
        m_dSBoxTransformScaleY->setValue(1);
        m_dSBoxTransformTranslateY = new QDoubleSpinBox(groupBox_4);
        m_dSBoxTransformTranslateY->setObjectName(QStringLiteral("m_dSBoxTransformTranslateY"));
        m_dSBoxTransformTranslateY->setEnabled(false);
        m_dSBoxTransformTranslateY->setGeometry(QRect(30, 230, 81, 22));
        m_dSBoxTransformScaleX = new QDoubleSpinBox(groupBox_4);
        m_dSBoxTransformScaleX->setObjectName(QStringLiteral("m_dSBoxTransformScaleX"));
        m_dSBoxTransformScaleX->setEnabled(false);
        m_dSBoxTransformScaleX->setGeometry(QRect(150, 200, 81, 22));
        m_dSBoxTransformScaleX->setMinimum(-1e+6);
        m_dSBoxTransformScaleX->setMaximum(100000);
        m_dSBoxTransformScaleX->setValue(1);
        label_25 = new QLabel(groupBox_4);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(130, 260, 16, 16));
        label_25->setAlignment(Qt::AlignCenter);
        m_LblCamPos_7 = new QLabel(groupBox_4);
        m_LblCamPos_7->setObjectName(QStringLiteral("m_LblCamPos_7"));
        m_LblCamPos_7->setGeometry(QRect(250, 180, 51, 16));
        label_26 = new QLabel(groupBox_4);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(250, 230, 16, 16));
        label_26->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(groupBox_4);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(10, 200, 16, 16));
        label_27->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(groupBox_4);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(130, 200, 16, 16));
        label_28->setAlignment(Qt::AlignCenter);
        m_dSBoxTransformScaleZ = new QDoubleSpinBox(groupBox_4);
        m_dSBoxTransformScaleZ->setObjectName(QStringLiteral("m_dSBoxTransformScaleZ"));
        m_dSBoxTransformScaleZ->setEnabled(false);
        m_dSBoxTransformScaleZ->setGeometry(QRect(150, 260, 81, 22));
        m_dSBoxTransformScaleZ->setValue(1);
        m_dSBoxTransformRotationY = new QDoubleSpinBox(groupBox_4);
        m_dSBoxTransformRotationY->setObjectName(QStringLiteral("m_dSBoxTransformRotationY"));
        m_dSBoxTransformRotationY->setEnabled(false);
        m_dSBoxTransformRotationY->setGeometry(QRect(270, 230, 81, 22));
        m_comboMaterial = new QComboBox(groupBox_4);
        m_comboMaterial->setObjectName(QStringLiteral("m_comboMaterial"));
        m_comboMaterial->setGeometry(QRect(10, 310, 151, 22));
        m_LblCamPos_8 = new QLabel(groupBox_4);
        m_LblCamPos_8->setObjectName(QStringLiteral("m_LblCamPos_8"));
        m_LblCamPos_8->setGeometry(QRect(10, 290, 51, 16));
        m_LEObjName = new QLineEdit(groupBox_4);
        m_LEObjName->setObjectName(QStringLiteral("m_LEObjName"));
        m_LEObjName->setGeometry(QRect(170, 310, 181, 20));
        label_44 = new QLabel(groupBox_4);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(170, 290, 47, 13));
        m_btnRemoveObj = new QPushButton(m_tabObjects);
        m_btnRemoveObj->setObjectName(QStringLiteral("m_btnRemoveObj"));
        m_btnRemoveObj->setGeometry(QRect(310, 220, 61, 23));
        m_btnAddObj = new QPushButton(m_tabObjects);
        m_btnAddObj->setObjectName(QStringLiteral("m_btnAddObj"));
        m_btnAddObj->setGeometry(QRect(260, 220, 41, 23));
        m_tabScene->addTab(m_tabObjects, QString());
        m_tabMaterial = new QWidget();
        m_tabMaterial->setObjectName(QStringLiteral("m_tabMaterial"));
        m_materialsList = new QListWidget(m_tabMaterial);
        m_materialsList->setObjectName(QStringLiteral("m_materialsList"));
        m_materialsList->setGeometry(QRect(10, 10, 361, 221));
        m_materialsList->setSelectionBehavior(QAbstractItemView::SelectItems);
        groupBox_5 = new QGroupBox(m_tabMaterial);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 280, 361, 201));
        label_37 = new QLabel(groupBox_5);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 100, 31, 16));
        label_37->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_SBoxDifColB = new QSpinBox(groupBox_5);
        m_SBoxDifColB->setObjectName(QStringLiteral("m_SBoxDifColB"));
        m_SBoxDifColB->setGeometry(QRect(60, 100, 61, 22));
        m_SBoxDifColB->setMaximum(255);
        m_LblCamPos_12 = new QLabel(groupBox_5);
        m_LblCamPos_12->setObjectName(QStringLiteral("m_LblCamPos_12"));
        m_LblCamPos_12->setGeometry(QRect(10, 20, 71, 16));
        label_38 = new QLabel(groupBox_5);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(10, 70, 41, 16));
        label_38->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_39 = new QLabel(groupBox_5);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(10, 40, 31, 16));
        label_39->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_SBoxDifColG = new QSpinBox(groupBox_5);
        m_SBoxDifColG->setObjectName(QStringLiteral("m_SBoxDifColG"));
        m_SBoxDifColG->setGeometry(QRect(60, 70, 61, 22));
        m_SBoxDifColG->setMaximum(255);
        m_SBoxDifColR = new QSpinBox(groupBox_5);
        m_SBoxDifColR->setObjectName(QStringLiteral("m_SBoxDifColR"));
        m_SBoxDifColR->setGeometry(QRect(60, 40, 61, 22));
        m_SBoxDifColR->setMaximum(255);
        label_40 = new QLabel(groupBox_5);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(130, 100, 31, 16));
        label_40->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_SBoxSpecColR = new QSpinBox(groupBox_5);
        m_SBoxSpecColR->setObjectName(QStringLiteral("m_SBoxSpecColR"));
        m_SBoxSpecColR->setGeometry(QRect(180, 40, 61, 22));
        m_SBoxSpecColR->setMaximum(255);
        label_41 = new QLabel(groupBox_5);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(130, 70, 41, 16));
        label_41->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_SBoxSpecColB = new QSpinBox(groupBox_5);
        m_SBoxSpecColB->setObjectName(QStringLiteral("m_SBoxSpecColB"));
        m_SBoxSpecColB->setGeometry(QRect(180, 100, 61, 22));
        m_SBoxSpecColB->setMaximum(255);
        m_SBoxSpecColG = new QSpinBox(groupBox_5);
        m_SBoxSpecColG->setObjectName(QStringLiteral("m_SBoxSpecColG"));
        m_SBoxSpecColG->setGeometry(QRect(180, 70, 61, 22));
        m_SBoxSpecColG->setMaximum(255);
        label_42 = new QLabel(groupBox_5);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(130, 40, 31, 16));
        label_42->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        m_CBoxIsSpec = new QCheckBox(groupBox_5);
        m_CBoxIsSpec->setObjectName(QStringLiteral("m_CBoxIsSpec"));
        m_CBoxIsSpec->setGeometry(QRect(130, 20, 81, 17));
        label_43 = new QLabel(groupBox_5);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(260, 20, 61, 16));
        m_SBoxShininess = new QSpinBox(groupBox_5);
        m_SBoxShininess->setObjectName(QStringLiteral("m_SBoxShininess"));
        m_SBoxShininess->setGeometry(QRect(260, 40, 61, 22));
        m_SBoxShininess->setMaximum(255);
        m_LEMaterialName = new QLineEdit(groupBox_5);
        m_LEMaterialName->setObjectName(QStringLiteral("m_LEMaterialName"));
        m_LEMaterialName->setGeometry(QRect(60, 130, 181, 20));
        label_45 = new QLabel(groupBox_5);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(10, 130, 47, 13));
        label_53 = new QLabel(groupBox_5);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(10, 160, 51, 16));
        m_LETextureFile = new QLineEdit(groupBox_5);
        m_LETextureFile->setObjectName(QStringLiteral("m_LETextureFile"));
        m_LETextureFile->setGeometry(QRect(60, 160, 181, 20));
        m_BtnBrowseTextFile = new QPushButton(groupBox_5);
        m_BtnBrowseTextFile->setObjectName(QStringLiteral("m_BtnBrowseTextFile"));
        m_BtnBrowseTextFile->setGeometry(QRect(250, 160, 51, 23));
        m_BtnMaterialAdd = new QPushButton(m_tabMaterial);
        m_BtnMaterialAdd->setObjectName(QStringLiteral("m_BtnMaterialAdd"));
        m_BtnMaterialAdd->setGeometry(QRect(260, 250, 41, 23));
        m_BtnMaterialRemove = new QPushButton(m_tabMaterial);
        m_BtnMaterialRemove->setObjectName(QStringLiteral("m_BtnMaterialRemove"));
        m_BtnMaterialRemove->setGeometry(QRect(310, 250, 61, 23));
        m_tabScene->addTab(m_tabMaterial, QString());

        m_layoutV->addWidget(m_tabScene);

        m_graphicView = new QGraphicsView(centralWidget);
        m_graphicView->setObjectName(QStringLiteral("m_graphicView"));
        m_graphicView->setGeometry(QRect(10, 10, 621, 531));
        m_BtnRender = new QPushButton(centralWidget);
        m_BtnRender->setObjectName(QStringLiteral("m_BtnRender"));
        m_BtnRender->setGeometry(QRect(260, 560, 75, 23));
        m_pBarRendering = new QProgressBar(centralWidget);
        m_pBarRendering->setObjectName(QStringLiteral("m_pBarRendering"));
        m_pBarRendering->setGeometry(QRect(20, 600, 601, 23));
        m_pBarRendering->setValue(0);
        RayCasterClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(RayCasterClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1037, 21));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        RayCasterClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(RayCasterClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        RayCasterClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(RayCasterClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        RayCasterClass->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuFile->addAction(m_actionNew);
        menuFile->addAction(m_actionOpen);
        menuFile->addAction(m_actionSave);
        menuFile->addAction(m_actionQuit);

        retranslateUi(RayCasterClass);

        m_tabScene->setCurrentIndex(0);
        m_objTab->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(RayCasterClass);
    } // setupUi

    void retranslateUi(QMainWindow *RayCasterClass)
    {
        RayCasterClass->setWindowTitle(QApplication::translate("RayCasterClass", "RayCaster", 0));
        m_actionNew->setText(QApplication::translate("RayCasterClass", "New", 0));
        m_actionOpen->setText(QApplication::translate("RayCasterClass", "Open", 0));
        m_actionSave->setText(QApplication::translate("RayCasterClass", "Save", 0));
        m_actionQuit->setText(QApplication::translate("RayCasterClass", "Quit", 0));
        m_grpBoxCamType->setTitle(QApplication::translate("RayCasterClass", "Camera type", 0));
        m_rBtnPerspectiveCam->setText(QApplication::translate("RayCasterClass", "Perspective Camera", 0));
        m_rBtnOrthogonalCam->setText(QApplication::translate("RayCasterClass", "Orthogonal Camera", 0));
        m_grpBoxCamProperties->setTitle(QApplication::translate("RayCasterClass", "Properties ", 0));
        m_LblCamPos->setText(QApplication::translate("RayCasterClass", "Position", 0));
        label->setText(QApplication::translate("RayCasterClass", "X:", 0));
        label_2->setText(QApplication::translate("RayCasterClass", "Y:", 0));
        label_3->setText(QApplication::translate("RayCasterClass", "Z:", 0));
        label_7->setText(QApplication::translate("RayCasterClass", "Angle:", 0));
        m_LblCamPos_2->setText(QApplication::translate("RayCasterClass", "Direction", 0));
        label_5->setText(QApplication::translate("RayCasterClass", "Y:", 0));
        label_6->setText(QApplication::translate("RayCasterClass", "X:", 0));
        label_4->setText(QApplication::translate("RayCasterClass", "Z:", 0));
        label_8->setText(QApplication::translate("RayCasterClass", "Y:", 0));
        label_9->setText(QApplication::translate("RayCasterClass", "X:", 0));
        m_LblCamPos_3->setText(QApplication::translate("RayCasterClass", "Up", 0));
        label_10->setText(QApplication::translate("RayCasterClass", "Z:", 0));
        groupBox->setTitle(QApplication::translate("RayCasterClass", "Image", 0));
        label_12->setText(QApplication::translate("RayCasterClass", "Height:", 0));
        label_11->setText(QApplication::translate("RayCasterClass", "Width:", 0));
        label_46->setText(QApplication::translate("RayCasterClass", "Filename:", 0));
        m_BtnBrowseImg->setText(QApplication::translate("RayCasterClass", "Browse", 0));
        m_tabScene->setTabText(m_tabScene->indexOf(m_tabCamera), QApplication::translate("RayCasterClass", "Camera", 0));
        groupBox_2->setTitle(QApplication::translate("RayCasterClass", "Lights", 0));
        m_BtnLightAdd->setText(QApplication::translate("RayCasterClass", "Add", 0));
        m_BtnLightRemove->setText(QApplication::translate("RayCasterClass", "Remove", 0));
        groupBox_3->setTitle(QApplication::translate("RayCasterClass", "Properties", 0));
        label_13->setText(QApplication::translate("RayCasterClass", "Y:", 0));
        label_14->setText(QApplication::translate("RayCasterClass", "Z:", 0));
        label_15->setText(QApplication::translate("RayCasterClass", "X:", 0));
        m_LblLightPosDir->setText(QApplication::translate("RayCasterClass", "Direction", 0));
        m_LblCamPos_4->setText(QApplication::translate("RayCasterClass", "Color", 0));
        label_16->setText(QApplication::translate("RayCasterClass", "Green:", 0));
        label_17->setText(QApplication::translate("RayCasterClass", "Blue:", 0));
        label_18->setText(QApplication::translate("RayCasterClass", "Red:", 0));
        m_rBtnPointLight->setText(QApplication::translate("RayCasterClass", "Point Light", 0));
        m_rBtnDirLight->setText(QApplication::translate("RayCasterClass", "Directional Light", 0));
        label_19->setText(QApplication::translate("RayCasterClass", "Name:", 0));
        groupBox_6->setTitle(QApplication::translate("RayCasterClass", "Background", 0));
        label_49->setText(QApplication::translate("RayCasterClass", "Red:", 0));
        label_48->setText(QApplication::translate("RayCasterClass", "Blue:", 0));
        m_LblCamPos_13->setText(QApplication::translate("RayCasterClass", "Color", 0));
        label_47->setText(QApplication::translate("RayCasterClass", "Green:", 0));
        m_LblCamPos_14->setText(QApplication::translate("RayCasterClass", "Ambient Light", 0));
        label_50->setText(QApplication::translate("RayCasterClass", "Green:", 0));
        label_51->setText(QApplication::translate("RayCasterClass", "Blue:", 0));
        label_52->setText(QApplication::translate("RayCasterClass", "Red:", 0));
        m_tabScene->setTabText(m_tabScene->indexOf(m_taLight), QApplication::translate("RayCasterClass", "Light", 0));
        groupBox_4->setTitle(QApplication::translate("RayCasterClass", "Properties", 0));
        label_29->setText(QApplication::translate("RayCasterClass", "Z:", 0));
        m_LblCamPos_9->setText(QApplication::translate("RayCasterClass", "Center", 0));
        label_30->setText(QApplication::translate("RayCasterClass", "X:", 0));
        label_31->setText(QApplication::translate("RayCasterClass", "Y:", 0));
        label_32->setText(QApplication::translate("RayCasterClass", "Radius", 0));
        m_objTab->setTabText(m_objTab->indexOf(m_tabSphere), QApplication::translate("RayCasterClass", "Sphere", 0));
        label_33->setText(QApplication::translate("RayCasterClass", "X:", 0));
        m_LblCamPos_10->setText(QApplication::translate("RayCasterClass", "Normal", 0));
        label_34->setText(QApplication::translate("RayCasterClass", "Y:", 0));
        label_35->setText(QApplication::translate("RayCasterClass", "Offset", 0));
        label_36->setText(QApplication::translate("RayCasterClass", "Z:", 0));
        m_objTab->setTabText(m_objTab->indexOf(m_tabPlane), QApplication::translate("RayCasterClass", "Plane", 0));
        m_btnBrowseMeshFile->setText(QApplication::translate("RayCasterClass", "Browse", 0));
        m_LblCamPos_11->setText(QApplication::translate("RayCasterClass", "File", 0));
        m_objTab->setTabText(m_objTab->indexOf(m_tabMesh), QApplication::translate("RayCasterClass", "Mesh", 0));
        m_CBObjTransform->setText(QApplication::translate("RayCasterClass", "Transform", 0));
        label_20->setText(QApplication::translate("RayCasterClass", "Y:", 0));
        label_21->setText(QApplication::translate("RayCasterClass", "Y:", 0));
        m_LblCamPos_5->setText(QApplication::translate("RayCasterClass", "Scale", 0));
        label_22->setText(QApplication::translate("RayCasterClass", "Z:", 0));
        m_LblCamPos_6->setText(QApplication::translate("RayCasterClass", "Translation", 0));
        label_23->setText(QApplication::translate("RayCasterClass", "Z:", 0));
        label_24->setText(QApplication::translate("RayCasterClass", "X:", 0));
        label_25->setText(QApplication::translate("RayCasterClass", "Z:", 0));
        m_LblCamPos_7->setText(QApplication::translate("RayCasterClass", "Rotation", 0));
        label_26->setText(QApplication::translate("RayCasterClass", "Y:", 0));
        label_27->setText(QApplication::translate("RayCasterClass", "X:", 0));
        label_28->setText(QApplication::translate("RayCasterClass", "X:", 0));
        m_LblCamPos_8->setText(QApplication::translate("RayCasterClass", "Material", 0));
        label_44->setText(QApplication::translate("RayCasterClass", "Name:", 0));
        m_btnRemoveObj->setText(QApplication::translate("RayCasterClass", "Remove", 0));
        m_btnAddObj->setText(QApplication::translate("RayCasterClass", "Add", 0));
        m_tabScene->setTabText(m_tabScene->indexOf(m_tabObjects), QApplication::translate("RayCasterClass", "Objects", 0));
        groupBox_5->setTitle(QApplication::translate("RayCasterClass", "Properties", 0));
        label_37->setText(QApplication::translate("RayCasterClass", "Blue:", 0));
        m_LblCamPos_12->setText(QApplication::translate("RayCasterClass", "Diffuse Color", 0));
        label_38->setText(QApplication::translate("RayCasterClass", "Green:", 0));
        label_39->setText(QApplication::translate("RayCasterClass", "Red:", 0));
        label_40->setText(QApplication::translate("RayCasterClass", "Blue:", 0));
        label_41->setText(QApplication::translate("RayCasterClass", "Green:", 0));
        label_42->setText(QApplication::translate("RayCasterClass", "Red:", 0));
        m_CBoxIsSpec->setText(QApplication::translate("RayCasterClass", "Specularity", 0));
        label_43->setText(QApplication::translate("RayCasterClass", "Shininess", 0));
        label_45->setText(QApplication::translate("RayCasterClass", "Name:", 0));
        label_53->setText(QApplication::translate("RayCasterClass", "Texture:", 0));
        m_BtnBrowseTextFile->setText(QApplication::translate("RayCasterClass", "Browse", 0));
        m_BtnMaterialAdd->setText(QApplication::translate("RayCasterClass", "Add", 0));
        m_BtnMaterialRemove->setText(QApplication::translate("RayCasterClass", "Remove", 0));
        m_tabScene->setTabText(m_tabScene->indexOf(m_tabMaterial), QApplication::translate("RayCasterClass", "Material", 0));
        m_BtnRender->setText(QApplication::translate("RayCasterClass", "Render", 0));
        menuFile->setTitle(QApplication::translate("RayCasterClass", "File", 0));
    } // retranslateUi

};

namespace Ui {
    class RayCasterClass: public Ui_RayCasterClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_RAYCASTER_H
